-- MySQL Script generated by MySQL Workbench
-- Sat Apr 19 13:46:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SyncTime
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SyncTime
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SyncTime` DEFAULT CHARACTER SET utf8 ;
USE `SyncTime` ;

-- -----------------------------------------------------
-- Table `SyncTime`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SyncTime`.`Location` (
  `idLocation` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Adress` VARCHAR(100) NULL,
  `Description` VARCHAR(200) NULL,
  `AddedAt` TIMESTAMP NULL,
  PRIMARY KEY (`idLocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SyncTime`.`Trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SyncTime`.`Trip` (
  `idTrip` INT NOT NULL,
  `IdUser` INT NOT NULL,
  `IdLocation` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `TripStart` VARCHAR(45) NULL,
  `TripEnd` VARCHAR(45) NULL,
  `Distance` FLOAT(5) NULL,
  `Time` FLOAT(5) NULL,
  `Guidance` TINYINT NULL,
  `Eta` DATETIME NULL,
  PRIMARY KEY (`idTrip`),
  INDEX `Iduser_idx` (`IdUser` ASC) VISIBLE,
  INDEX `IdLocation_idx` (`IdLocation` ASC) VISIBLE,
  CONSTRAINT `Iduser`
    FOREIGN KEY (`IdUser`)
    REFERENCES `SyncTime`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdLocation`
    FOREIGN KEY (`IdLocation`)
    REFERENCES `SyncTime`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SyncTime`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SyncTime`.`User` (
  `idUser` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Email` VARCHAR(50) NULL,
  `Username` VARCHAR(20) NULL,
  `Password` VARCHAR(20) NULL,
  `Location` VARCHAR(100) NULL,
  `CreatedAt` TIMESTAMP NULL,
  `Tracking` TINYINT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  CONSTRAINT `IdUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `SyncTime`.`Trip` (`idTrip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SyncTime`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SyncTime`.`Review` (
  `idReview` INT NOT NULL,
  `IdLocation` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(300) NULL,
  `Rating` FLOAT NULL,
  `CreatedAt` TIMESTAMP NULL,
  `Reviewcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idReview`),
  INDEX `IdLocation_idx` (`IdLocation` ASC) VISIBLE,
  CONSTRAINT `IdLocation`
    FOREIGN KEY (`IdLocation`)
    REFERENCES `SyncTime`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SyncTime`.`Notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SyncTime`.`Notifications` (
  `idNotifications` INT NOT NULL,
  `IdUser` INT NOT NULL,
  `IdTrip` INT NULL,
  `Message` VARCHAR(300) NULL,
  `Time` TIMESTAMP NULL,
  PRIMARY KEY (`idNotifications`),
  INDEX `IdUser_idx` (`IdUser` ASC) VISIBLE,
  INDEX `IdTrip_idx` (`IdTrip` ASC) VISIBLE,
  CONSTRAINT `IdUser`
    FOREIGN KEY (`IdUser`)
    REFERENCES `SyncTime`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdTrip`
    FOREIGN KEY (`IdTrip`)
    REFERENCES `SyncTime`.`Trip` (`idTrip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SyncTime`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SyncTime`.`Group` (
  `idGroup` INT NOT NULL,
  `idUser` INT NULL,
  `GroupName` VARCHAR(45) NULL,
  `Description` VARCHAR(200) NULL,
  PRIMARY KEY (`idGroup`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
